version: '3.8'

services:
  # 1. APLIKASI UTAMA (WEBSITE)
  app-saya:
    build: .
    ports:
      - "8080:3300"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    # ðŸ‘‡ INI BENAR: Menjalankan file website (app_final.js)
    command: npx nodemon server.js
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - rabbitmq

  # 2. EMAIL SERVICE (TUKANG POS)
  email-service:
    build: .
    # ðŸ‘‡ INI YANG DIPERBAIKI: Menjalankan script worker (email-service.js)
    command: npx nodemon email-service.js
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      rabbitmq:
        condition: service_healthy

  # 3. RABBITMQ (KANTOR POS)
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Jalur Surat
      - "15672:15672" # Jalur Dashboard
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5