version: '3.8'

services:
  # 1. APLIKASI UTAMA (WEBSITE)
  app-saya:
    build: .
    ports:
      - "8080:3300"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      # ðŸ‘‡ TAMBAHAN KONEKSI DATABASE:
      - DB_USER=postgres
      - DB_PASS=password123
      - DB_NAME=asuransi_db
      - DB_HOST=db
    command: node server.js
    depends_on:
      - rabbitmq
      - db # Tunggu database nyala dulu

  # 2. EMAIL SERVICE (TUKANG POS)
  email-service:
    build: .
    command: node email-service.js
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy

  # 3. RABBITMQ (KANTOR POS)
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 4. DATABASE POSTGRESQL (LEVEL 3 - BARU!)
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: asuransi_db
    volumes:
      - pgdata:/var/lib/postgresql/data # Kunci biar data AWET
    ports:
      - "5432:5432"

# DEFINISI VOLUME (Harddisk Virtual)
volumes:
  pgdata: