apiVersion: v1
kind: Secret
metadata:
  name: rahasia-aplikasi-saya  # Nama brankasnya
type: Opaque
stringData:
  # Masukkan isi REDIS_URL dari file .env kamu di sini
  REDIS_URL: "redis://default:l3Wq87AEP5EFhz4uqtGVVv2HRO8IU8bq@redis-10860.c280.us-central1-2.gce.cloud.redislabs.com:10860"
  PORT_APP: "3300"